### ISSUE TITLE
Thoughts about changes re: TypeScript 2.8?

### ISSUE THREAD

**Issue by fbartho** [pelotom/type-zoo#13]
Context: `Omit` is easier to implement now:
https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-377567046

Should we think about pulling that implementation in? What other types can be improved?

**Comment by pelotom** [comment]
Yep, I'm all for it. Care to open a PR?

**Comment by fbartho** [comment]
@pelotom I'm happy to open a PR for the Omit & Overwrite updated implementations from that thread, but I don't know if I'm expert enough at TypeScript to know if they're actually better, or to know what other changes might be recommended.

**Comment by pelotom** [comment]
@fbartho That’s what unit tests and code review are for, so just give it a go! And if there are other changes to be made, they’ll come to light in due course and future PRs can address them.

**Comment by fbartho** [comment]
Ran into a couple roadblocks this evening:
- dtslint doesn't support TypeScript 2.8 -- https://github.com/Microsoft/dtslint/issues/113
- because definitelytyped-header-parser doesn't support TypeScript 2.8 -- https://github.com/Microsoft/definitelytyped-header-parser/pull/12

I'm still going ahead with my changes, and I'm just manually patching definitelytyped-header-parser in my node_modules, but I imagine that's probably going to block you from wanting to merge.
