### ISSUE TITLE
Feature Idea: Pick2 Pick3 -- deeper nested picking!

### ISSUE THREAD

**Issue by fbartho** [pelotom/type-zoo#15]
https://gist.github.com/staltz/368866ea6b8a167fbdac58cddf79c1bf

Basically: `Pick<>` only unpacks one level. It'd be nice to be able to pick deeper into nested objects!

**Comment by pelotom** [comment]
This looks useful, want to submit a PR?

**Comment by fbartho** [comment]
Implemented in #16
