### ISSUE TITLE
Required<T> broken with Typescript 2.9

### ISSUE THREAD

**Issue by marcind** [pelotom/type-zoo#18]
Now that Typescript produces something assignable to `string | number | symbol` for `keyof T`, the [definition of Required<T>](https://github.com/pelotom/type-zoo/blob/9e5736465cdbcdc14357a7ce594f20c234857c85/types/index.d.ts#L46) yields this error:

```
Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

46   [P in Purify<keyof T>]: NonNullable<T[P]>;
```

Projects using type-zoo could use the `"keyofStringsOnly": true` compiler option as a workaround for the time being.

Longer term, the definition of `Purify` could be updated to `export type Purify<T extends string | number | symbol> = { [P in T]: T; }[T];`, however this is a breaking change for previous versions of TypeScript.

An alternative would be to declare something like `type Purify2<O, T extends keyof O> = { [P in T]: T; }[T];` and have `Required<T>` use that instead.

Thoughts? I can send a PR.

**Comment by pelotom** [comment]
`Required` should just be removed from the library--it's shipped in `lib.d.ts` since 2.8.

For migrating to 2.9, in addition to fixing `Purify` for non-`string` keys, `unknown` needs to be removed because it's now built in and a reserved keyword.

A PR would be welcome, however I think we will be blocked on dtslint being able to parse a minimimum version string of 2.9.

**Comment by marcind** [comment]
I hope to have some time to give Required/Purify a shot in a little while, though if anyone beats me to it that's great too.

Re: `unknown`, the change is checked in but not slated to ship until [TS 3.0](https://github.com/Microsoft/TypeScript/wiki/Roadmap#30-july-2018)

**Comment by pelotom** [comment]
> Re: unknown, the change is checked in but not slated to ship until TS 3.0

Ah, my mistake.

**Comment by marcind** [comment]
Ok, PR is up. It only removes `Required<T>` and keeps `Purify`, since that type does not use `keyof`. Not sure in what scenarios people are using it so I didn't want to make changes going in blind.
