### ISSUE TITLE
Intersection types and Omit

### ISSUE THREAD

**Issue by ekilah** [pelotom/type-zoo#21]
Hi,

I'm fairly deep into my recent need to understand/learn Typescript's type system, and am using `type-zoo` as well. I've run into an issue with `Omit` that I don't understand, so I've made an example here to ask you about it: 

[typescript playground link](https://www.typescriptlang.org/play/#src=%2F%2F%20This%20is%20the%20definition%20of%20Omit%20from%20type-zoo%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%0D%0A%0D%0Atype%20Foo%20%3D%20%7B%0D%0A%20%20%20%20x%3F%3A%20string%0D%0A%20%20%20%20willOmitThis%3F%3A%20any%0D%0A%7D%0D%0A%0D%0Atype%20Bar%20%3D%20%7B%0D%0A%20%20%20%20y%3F%3A%20number%0D%0A%20%20%20%20willOmitThis%3F%3A%20any%0D%0A%7D%0D%0A%0D%0A%2F%2F%20----------%0D%0A%2F%2F%20below%2C%20trying%20different%20ways%20to%20define%20a%20new%20Bar.%0D%0A%2F%2F%20in%20this%20version%2C%20we%20want%20to%20omit%20something%20and%20add%20something.%0D%0A%2F%2F%20----------%0D%0A%0D%0Atype%20NewBarOmit%20%3D%20Omit%3CBar%2C%20'willOmitThis'%3E%20%26%20%7B%0D%0A%20%20addedToBar%3F%3A%20string%5B%5D%0D%0A%7D%0D%0A%0D%0Atype%20NewBar%20%3D%20%7B%0D%0A%20%20%20%20y%3F%3A%20number%0D%0A%20%20%20%20addedToBar%3F%3A%20string%5B%5D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20-----------%0D%0A%0D%0A%0D%0A%2F%2F%20-----------%0D%0A%2F%2F%20here%2C%20trying%20different%20ways%20to%20define%20a%20new%20Foo.%0D%0A%2F%2F%20in%20this%20version%2C%20we%20want%20to%20omit%20something%20and%20add%20something.%0D%0A%2F%2F%20the%20%60Omit%60%20version%20doesn't%20cause%20the%20expected%20type-system%20error%20%0D%0A%2F%2F%20when%20a%20non-specified%20key%20is%20provided%2C%20the%20other%20version%20does.%0D%0A%2F%2F%20-----------%0D%0A%0D%0Atype%20NewFooOmit%20%3D%20Omit%3CFoo%2C%20'willOmitThis'%3E%20%26%20%7B%0D%0A%20%20addedToFoo%3F%3A%20NewBar%20%2F%2F%20or%20NewBarOmit%2C%20doesn't%20matter%0D%0A%7D%0D%0A%0D%0Atype%20NewFoo%20%3D%20%7B%0D%0A%20%20x%3F%3A%20string%0D%0A%20%20addedToFoo%3F%3A%20NewBar%20%2F%2F%20or%20NewBarOmit%2C%20doesn't%20matter%0D%0A%7D%0D%0A%0D%0A%2F%2F%20-----------%0D%0A%0D%0A%2F*%20%60x%3A%20NewFoo%60%20fails%20correctly%2C%20%60x%3A%20NewFooOmit%60%20doesn't%20fail%2C%20though%20it%20should%3F%20*%2F%0D%0Aconst%20x%3A%20NewFoo%20%3D%20%7B%0D%0A%20%20%20%20addedToFoo%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20addedToBar%3A%20%5B'test'%5D%2C%0D%0A%20%20%20%20%20%20%20%20somethingElse%3A%20'doesnt%20fail%20when%20x%20is%20of%20type%20NewFooOmit%2C%20why%3F'%2C%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20%2F%2F%20baz%3A%20'fails%20in%20all%20cases%20when%20included%2C%20as%20expected'%2C%0D%0A%7D%0D%0A)

here's the code (same as in the playground above):

```ts
// This is the definition of Omit from type-zoo
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

type Foo = {
    x?: string
    willOmitThis?: any
}

type Bar = {
    y?: number
    willOmitThis?: any
}

// ----------
// below, trying different ways to define a new Bar.
// in this version, we want to omit something and add something.
// ----------

type NewBarOmit = Omit<Bar, 'willOmitThis'> & {
  addedToBar?: string[]
}

type NewBar = {
    y?: number
    addedToBar?: string[]
}

// -----------


// -----------
// here, trying different ways to define a new Foo.
// in this version, we want to omit something and add something.
// the `Omit` version doesn't cause the expected type-system error 
// when a non-specified key is provided, the other version does.
// -----------

type NewFooOmit = Omit<Foo, 'willOmitThis'> & {
  addedToFoo?: NewBar // or NewBarOmit, doesn't matter
}

type NewFoo = {
  x?: string
  addedToFoo?: NewBar // or NewBarOmit, doesn't matter
}

// -----------

/* `x: NewFoo` fails correctly, `x: NewFooOmit` doesn't fail, though it should? */
const x: NewFoo = {
    addedToFoo: {
        addedToBar: ['test'],
        somethingElse: 'doesnt fail when x is of type NewFooOmit, why?',
    },
    // baz: 'fails in all cases when included, as expected',
}
```

I don't understand why the type system doesn't care that `somethingElse` is not an allowed key of the object with type `NewBar` if I defined `NewBar` with `Omit`.

Is this something about intersection types (the use of the `&` after the `Omit`) that I don't understand correctly? Or maybe something else, or an issue with `Omit` perhaps? My understanding of intersection types is that the `&` just combines two type definitions together to create a new type, but that doesn't seem to be correct.

(Sorry if this turns out to not be an question specific to `type-zoo` and instead about TS, but I wasn't sure).

thanks!

**Comment by pelotom** [comment]
It looks like you're running into the fact that [excess property checking is disabled for intersection types](https://github.com/Microsoft/TypeScript/issues/18075).

**Comment by ekilah** [comment]
@pelotom thanks for the link, this stuff is not easy to google around for. It does seem like that is the same bug as I'm describing, and as I was wondering, it doesn't seem to have to do with `type-zoo` specifically... thanks for the help! (and `type-zoo`)
