### ISSUE TITLE
Idea: Type Unpackers for Function Parameters

### ISSUE THREAD

**Issue by fbartho** [pelotom/type-zoo#22]
Because of TypeScript 2.8 Conditional Types, we can now do the following:

```typescript
type Param0<Func> = Func extends (a: infer T, ...args: any[]) => any
	? T
	: never;
type T0 = Param0<() => void>; // {}
type T1 = Param0<(a: number) => void>; // number
type T2 = Param0<(a: string[]) => void>; // string[]
```

Issue for discussion!

Questions:

- Naming scheme?
- Multiple Parameter Unpacks at the same time?

See also `ReturnType<Func>`

**Comment by pelotom** [comment]
Great idea! What about just one operator which returns a tuple of types?

```ts
type ParamTypes<F extends Function> =
  F extends () => any ? {} :
  F extends (p0: infer P0) => any ? [P0] :
  F extends (p0: infer P0, p1: infer P1) => any ? [P0, P1] :
  F extends (p0: infer P0, p1: infer P1, p2: infer P2) => any ? [P0, P1, P2] :
  // ...
  never;

type T0 = ParamTypes<() => void>; // {}
type T1 = ParamTypes<(a: number) => void>; // [number]
type T2 = ParamTypes<(a: string, b: boolean) => void>; // [string, boolean]
```

Then you can further access particular indexes as you please, e.g.

```ts
type Third = ParamTypes<typeof f>[2];
```

I used `ParamTypes` for consistency with `ReturnType`; I could also be convinced `Parameters` or `Params` is a good name...

**Comment by kourge** [comment]
`ArgumentsType` seems more consistent, in line with `arguments` as well as `(...args: any[])`.

**Comment by fbartho** [comment]
@kourge That's a great point. Consistent options:

- `ArgumentsType`
- `ArgumentTypes`
- `ArgumentType` (plural is implied by operator's type-tuple return?).

@pelotom Is there a performance concern re: unpacking the whole array by default? If people are mostly going to access a single parameter, maybe we should consider that?

**Comment by pelotom** [comment]
> `ArgumentsType` seems more consistent, in line with `arguments` as well as `(...args: any[])`.

Parameters are the declared inputs of a function signature, arguments are the runtime objects passed to a function:

https://stackoverflow.com/questions/156767/whats-the-difference-between-an-argument-and-a-parameter

> @pelotom Is there a performance concern re: unpacking the whole array by default? If people are mostly going to access a single parameter, maybe we should consider that?

I really doubt there's much performance difference.

**Comment by pelotom** [comment]
On second thought you may be right about performance being a concern... I agree it might be better to play it safe.

**Comment by fbartho** [comment]
@pelotm I’d be happy with N short helpers, and also providing an up-to-N batch unpacker. (With a performance warning)

Then naming wise, should it be:

- ParamN
- ParameterTypeN

(Where N is a number) or should it be something else?

**Comment by fbartho** [comment]
(I think the final name of the short form will influence our long form name)

**Comment by pelotom** [comment]
I think I'd actually vote `ParamN` (what you originally had).

**Comment by chocolateboy** [comment]
Is this the same as the built-in [`Parameters`](https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype) type (which doesn't have a restriction on the number of parameters)?

https://github.com/microsoft/TypeScript/blob/eca8957430bf52cfdfa2bfe03c9431682da6a558/lib/lib.es5.d.ts#L1514

If so, does it have the same limitation (only returns the [first](https://github.com/microsoft/TypeScript/issues/26591) overloaded parameters)?

**Comment by fbartho** [comment]
@chocolateboy I believe these are equivalent implementations. The built-in one didn't exist when we added this one, as far as I know.

As such I expect it to be subject to the same limits. But you should test it and let us know! 

We don't use many overridden method definitions in our codebase, because the syntax could be confusing.
