### ISSUE TITLE
Omit and union types

### ISSUE THREAD

**Issue by OliverJAsh** [pelotom/type-zoo#29]
Currently, if a union type is given to `Omit`, the returned type does not correctly preserve the union type, e.g. this test fails:

``` ts
declare const foo: Omit<{ shared: string; } & ({ x: boolean } | { y: string }), 'shared'>;

/* $ExpectType Pick<{
    shared: string;
} & {
    x: boolean;
}, "x"> | Pick<{
    shared: string;
} & {
    y: string;
}, "y"> */
foo;
```

`foo` instead has type

``` ts
Pick<({
    shared: string;
} & {
    x: boolean;
}) | ({
    shared: string;
} & {
    y: string;
}), never>
```

We can use conditional types to fix this:

``` ts
export type Omit<T, K extends keyof any> = T extends any ? Pick<T, Exclude<keyof T, K>> : never;
```

https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-378589263

We might also want to apply this fix to some of the other helpers?

**Comment by pelotom** [comment]
@OliverJAsh sounds good, want to open a PR?
