### ISSUE TITLE
Interest in `ExtractStrict`?

### ISSUE THREAD

**Issue by ekilah** [pelotom/type-zoo#37]
Any interest / reason to not want this type added? I can make a PR if so:

```ts
type ExtractStrict<T, U extends T> = T extends U ? T : never
```

context: 

- https://github.com/microsoft/TypeScript/issues/30738
- https://github.com/Microsoft/TypeScript/issues/30825
- https://github.com/pelotom/type-zoo/pull/31

Seems like the TS team's reasoning for making their official `Omit` non-strict included the fact that `Extract` was also non-strict, which is something I just ran into wanting. Just like `OmitStrict`, `ExtractStrict` will get the compiler to help out during refactoring things like this, or to prevent typos in the string keys:

```ts
export type TSomeColorOptions = ExtractStrict<TColor, 'blue' | 'whitee'> // should error for typo
```

**Comment by pelotom** [comment]
Sure, I'd take a PR for that. Also might as well add `ExcludeStrict`.
