### ISSUE TITLE
Overlapping string unions

### ISSUE THREAD

**Issue by dalegaard** [pelotom/type-zoo#5]
Hi, love the project!

Would you consider adding a type for overlapping string unions? It should be implementable directly based on the existing `Diff`:
```typescript
type Overlap<T extends string, U extends string> = Diff<T, Diff<T, U>>;
```
I'm not sure what would be the best name for the thing, but `Overlap` seems descriptive and in line with the existing types in this library.

Best regards!

**Comment by pelotom** [comment]
Seems good to me, care to submit a PR?

**Comment by tycho01** [comment]
sounds like the `Extract` in TS `master` :), but admittedly that probably won't be available to most people yet for a while...

**Comment by pelotom** [comment]
Yeah, when 2.8 is incorporated in the next major version of `type-zoo`, it probably makes sense for some operators which are now redundant to be removed, and for other operators which are newly possible, e.g. `DeepPartial`, to be added.
